repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.5.0"
  hooks:
  -   id: check-docstring-first
  -   id: check-added-large-files
      args: ['--maxkb=10000']
 
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  -   id: flake8
      args: ['--ignore=E129,W504']