stages:
  train_test_split:
    cmd: python3 src/train_test_split.py
    deps:
    - src/train_test_split.py
    - src/utils/dvc/params.py
    - data/raw
    params:
    - train_test_split.split_ratio
    - train_test_split.shuffle
    - train_test_split.seed
    outs:
    - data/processed/train
    - data/processed/test

# *** ---------------------------------------------

  augmentation_visualisation:
    cmd: python3 src/augmentation_visualisation.py
    deps:
    - src/augmentation_visualisation.py
    - src/utils/data/tensorflow_based.py
    - src/utils/dvc/params.py
    - data/processed/train
    params:
    - augmentation_visualisation.random_crop
    - augmentation_visualisation.random_flip
    - augmentation_visualisation.random_rotation
    - augmentation_visualisation.random_zoom
    - augmentation_visualisation.random_brightness
    - augmentation_visualisation.random_contrast
    - augmentation_visualisation.random_translation_height
    - augmentation_visualisation.random_translation_width
    plots:
    - data/interim/augmentation_visualisation/augmented_images.png:
        cache: false