stages:
  dataset_split:
    cmd: python3 src/dataset_split.py
    deps:
    - src/dataset_split.py
    - src/utils/misc.py
    - src/utils/dvc/params.py
    - data/raw/${all.dataset}
    params:
    - dataset_split.split_ratio
    - dataset_split.shuffle
    - all.seed
    - all.dataset
    outs:
    - data/processed/${all.dataset}/train
    - data/processed/${all.dataset}/val
    - data/processed/${all.dataset}/test

# *** ---------------------------------------------

  extract_complexity:
    cmd: python3 src/extract_complexity.py
    deps:
    - src/extract_complexity.py
    - src/utils/data/jpegmse.py
    - src/utils/data/complexityaux.py
    - src/utils/dvc/params.py
    - src/utils/misc.py
    - data/processed/${all.dataset}/train
    - data/processed/${all.dataset}/val
    - data/processed/${all.dataset}/test
    - data/raw/general/all
    params:
    - all.dataset
    - all.grayscale
    - all.scale
    outs:
    - data/processed/${all.dataset}/tabular/complexity.csv
    plots:
    - visualisation/${all.dataset}/complexity_hist.png:
        cache: false
        persist: true

# *** ---------------------------------------------

  cae_hp_tuning:
    cmd: python3 src/cae_hp_tuning.py
    deps:
    - src/cae_hp_tuning.py
    - src/utils/dvc/params.py
    - src/utils/misc.py
    - src/utils/models/kerasaux.py
    - src/utils/models/ktmodels.py
    - src/utils/data/tfdatasets.py
    - data/processed/${all.dataset}/train
    - data/processed/${all.dataset}/val
    params:
    - all.random_crop
    - all.random_flip
    - all.random_rotation
    - all.random_zoom
    - all.random_brightness
    - all.random_contrast
    - all.random_translation_height
    - all.random_translation_width
    - all.input_size
    - all.scale
    - all.grayscale
    - all.dataset
    - all.seed
    - cae_hp_tuning.batch_size
    - cae_hp_tuning.bottleneck_filters
    - cae_hp_tuning.alpha
    - cae_hp_tuning.beta
    - cae_hp_tuning.patience
    - cae_hp_tuning.revive_best
    - cae_hp_tuning.early_stopping
    - cae_hp_tuning.epochs
    - cae_hp_tuning.min_lr
    - cae_hp_tuning.max_trials
    outs:
    - models/${all.dataset}/logs/hp_search/CAE
    - models/${all.dataset}/logs/hp_search/tb
    - models/${all.dataset}/bin/hp_search_best.hdf5
    - models/${all.dataset}/logs/hp_search/hp_search_results.json
    
# *** ---------------------------------------------

  cae_pretraining:
    cmd: python3 src/cae_pretraining.py
    deps:
    - src/cae_pretraining.py
    - src/utils/dvc/params.py
    - src/utils/models/kerasaux.py
    - src/utils/data/tfdatasets.py
    - src/utils/misc.py
    - data/raw/tiny-imagenet-200
    - models/${all.dataset}/bin/hp_search_best.hdf5
    params:
    - all.random_crop
    - all.random_flip
    - all.random_rotation
    - all.random_zoom
    - all.random_brightness
    - all.random_contrast
    - all.random_translation_height
    - all.random_translation_width
    - all.input_size
    - all.scale
    - all.grayscale
    - all.dataset
    - all.seed
    - cae_pretraining.batch_size
    - cae_pretraining.alpha
    - cae_pretraining.beta
    - cae_pretraining.patience
    - cae_pretraining.revive_best
    - cae_pretraining.early_stopping
    - cae_pretraining.epochs
    - cae_pretraining.min_lr
    - cae_pretraining.learning_rate
    outs:
    - models/${all.dataset}/bin/pretrained_cae.hdf5
    - models/${all.dataset}/logs/pretraining_history.csv: 
        persist: true


# *** ---------------------------------------------

  cae_training:
    cmd: python3 src/cae_training.py
    deps:
    - src/cae_training.py
    - src/utils/dvc/params.py
    - src/utils/models/kerasaux.py
    - src/utils/data/tfdatasets.py
    - data/processed/${all.dataset}/train
    - data/processed/${all.dataset}/val
    - models/${all.dataset}/bin/pretrained_cae.hdf5
    params:
    - all.random_crop
    - all.random_flip
    - all.random_rotation
    - all.random_zoom
    - all.random_brightness
    - all.random_contrast
    - all.random_translation_height
    - all.random_translation_width
    - all.input_size
    - all.scale
    - all.grayscale
    - all.dataset
    - all.seed
    - cae_training.batch_size
    - cae_training.alpha
    - cae_training.beta
    - cae_training.patience
    - cae_training.revive_best
    - cae_training.early_stopping
    - cae_training.epochs
    - cae_training.min_lr
    outs:
    - models/${all.dataset}/bin/trained_cae.hdf5
    - models/${all.dataset}/logs/training_history.csv:
        persist: true

# *** ---------------------------------------------

  calculate_reconstruction_mse:
    cmd: python3 src/calculate_reconstruction_mse.py
    deps:
    - src/calculate_reconstruction_mse.py
    - src/utils/dvc/params.py
    - models/${all.dataset}/bin/trained_cae.hdf5
    - src/utils/data/complexityaux.py
    - data/processed/${all.dataset}/train
    - data/processed/${all.dataset}/val
    - data/processed/${all.dataset}/test
    params:
    - all.dataset
    - all.grayscale
    - all.scale
    outs:
    - data/processed/${all.dataset}/tabular/cae_mse.csv
    plots:
    - visualisation/${all.dataset}/caemse_hist.png:
        cache: false
        persist: true

# *** ---------------------------------------------

  merge_complexity_caemse:
    cmd: python3 src/merge_complexity_caemse.py
    deps:
    - src/merge_complexity_caemse.py
    - src/utils/dvc/params.py
    - data/processed/${all.dataset}/tabular/complexity.csv
    - data/processed/${all.dataset}/tabular/cae_mse.csv
    params:
    - all.dataset
    outs:
    - data/processed/${all.dataset}/tabular/complexity_caemse.csv
    plots:
    - visualisation/${all.dataset}/complexity_vs_caemse.html:
        cache: false
        persist: true

# *** ---------------------------------------------

  train_classifier_models:
    cmd: python3 src/train_classifier_models.py
    deps:
    - src/train_classifier_models.py
    - src/utils/dvc/params.py
    - src/utils/misc.py
    - data/processed/${all.dataset}/tabular/complexity_caemse.csv
    params:
    - all.dataset
    - train_classifier_models.models_score_func
    - train_classifier_models.models_n_iter
    - train_classifier_models.models_n_splits
    outs:
    - models/${all.dataset}/bin/logistic_regression_combined.joblib
    - models/${all.dataset}/bin/logistic_regression_autoencoder.joblib
    - models/${all.dataset}/bin/logistic_regression_complexity.joblib

# *** ---------------------------------------------

  evaluate:
    cmd: python3 src/evaluate.py
    deps:
    - src/evaluate.py
    - src/utils/dvc/params.py
    - src/utils/evaluation/classification_metrics.py
    - data/processed/${all.dataset}/tabular/cae_mse.csv
    - data/processed/${all.dataset}/tabular/complexity.csv
    - models/${all.dataset}/bin/logistic_regression_combined.joblib
    - models/${all.dataset}/bin/logistic_regression_autoencoder.joblib
    - models/${all.dataset}/bin/logistic_regression_complexity.joblib
    metrics:
    - metrics/${all.dataset}/autoencoder_metrics.json:
        cache: false
        persist: true
    - metrics/${all.dataset}/complexity_metrics.json:
        cache: false
        persist: true
    - metrics/${all.dataset}/combined_metrics.json:
        cache: false
        persist: true
    outs:
    - visualisation/${all.dataset}/autoencoder_confusion_matrix.png:
        cache: false
        persist: true
    - visualisation/${all.dataset}/complexity_confusion_matrix.png:
        cache: false
        persist: true
    - visualisation/${all.dataset}/combined_confusion_matrix.png:
        cache: false
        persist: true

# *** ---------------------------------------------

  metrify_reconstruction:
    cmd: python3 src/metrify_reconstruction.py
    deps:
    - src/metrify_reconstruction.py
    - src/utils/dvc/params.py
    - data/processed/${all.dataset}/tabular/cae_mse.csv
    outs:
    - metrics/${all.dataset}/reconstruction_data.csv:
        cache: false
    - visualisation/${all.dataset}/reconstruction_metrics.html:
        cache: false
        persist: true
    metrics:
    - metrics/${all.dataset}/reconstruction_metrics.json:
        cache: false
        persist: true
