stages:
  dataset_split:
    cmd: python3 src/dataset_split.py
    deps:
    - src/dataset_split.py
    - data/raw
    params:
    - dataset_split.split_ratio
    - dataset_split.shuffle
    - all.seed
    outs:
    - data/processed/train
    - data/processed/val
    - data/processed/test

# *** ---------------------------------------------

  extract_complexity:
    cmd: python3 src/extract_complexity.py
    deps:
    - src/extract_complexity.py
    - src/utils/data/jpegmse.py
    - src/utils/data/complexityaux.py
    - data/processed/train
    - data/processed/test
    outs:
    - data/processed/tabular/complexity.csv
    plots:
    - visualisation/complexity/train_ok_front_hist.png:
        cache: false
    - visualisation/complexity/val_ok_front_hist.png:
        cache: false
    - visualisation/complexity/train_def_front_hist.png:
        cache: false
    - visualisation/complexity/val_def_front_hist.png:
        cache: false
# *** ---------------------------------------------

  cae_hp_tuning:
    cmd: python3 src/cae_hp_tuning.py
    deps:
    - src/cae_hp_tuning.py
    - src/utils/models/kerascallbacks.py
    - src/utils/models/ktmodels.py
    - src/utils/data/tfdatasets.py
    - data/processed/train
    - data/processed/val
    params:
    - all.random_crop
    - all.random_flip
    - all.random_rotation
    - all.random_zoom
    - all.random_brightness
    - all.random_contrast
    - all.random_translation_height
    - all.random_translation_width
    - cae_hp_tuning.batch_size
    - cae_hp_tuning.bottleneck_filters
    - cae_hp_tuning.alpha
    - cae_hp_tuning.beta
    - cae_hp_tuning.patience
    - cae_hp_tuning.revive_best
    - cae_hp_tuning.early_stopping
    - cae_hp_tuning.epochs
    - cae_hp_tuning.min_lr
    - cae_hp_tuning.max_trials
    - cae_hp_tuning.log_path

    outs:
    - models/logs
  
# *** ---------------------------------------------

  augmentation_visualisation:
    cmd: python3 src/augmentation_visualisation.py
    deps:
    - src/augmentation_visualisation.py
    - src/utils/data/tfdatasets.py
    - data/processed/train
    params:
    - all.random_crop
    - all.random_flip
    - all.random_rotation
    - all.random_zoom
    - all.random_brightness
    - all.random_contrast
    - all.random_translation_height
    - all.random_translation_width
    - all.input_size
    plots:
    - visualisation/augmentation/augmented_images.png:
        cache: false

# *** ---------------------------------------------

  reconstruction_visualisation:
    cmd: python3 src/reconstruction_visualisation.py
    deps:
    - src/reconstruction_visualisation.py
    - src/utils/data/tfdatasets.py
    - data/processed/train
    - models/best_cae.hdf5
    params:
    - all.input_size
    plots:
    - visualisation/reconstruction/reconstructed_images.png:
        cache: false

# *** ---------------------------------------------

  cae_training:
    cmd: python3 src/cae_training.py
    deps:
    - src/cae_training.py
    - src/utils/models/kerascallbacks.py
    - src/utils/data/tfdatasets.py
    - data/processed/train
    - data/processed/val
    - models/logs/hp_search_best.hdf5
    params:
    - all.random_crop
    - all.random_flip
    - all.random_rotation
    - all.random_zoom
    - all.random_brightness
    - all.random_contrast
    - all.random_translation_height
    - all.random_translation_width
    - cae_training.batch_size
    - cae_training.alpha
    - cae_training.beta
    - cae_training.patience
    - cae_training.revive_best
    - cae_training.early_stopping
    - cae_training.epochs
    - cae_training.min_lr
    - cae_training.learning_rate
    outs:
    - models/best_cae.hdf5
    - models/training_history.csv

# *** ---------------------------------------------

  calculate_reconstruction_mse:
    cmd: python3 src/calculate_reconstruction_mse.py
    deps:
    - src/calculate_reconstruction_mse.py
    - models/best_cae.hdf5
    - src/utils/data/complexityaux.py
    - data/processed/train
    - data/processed/val
    - data/processed/test
    outs:
    - data/processed/tabular/cae_mse.csv
    plots:
    - visualisation/reconstruction/train_ok_front_hist.png:
        cache: false
    - visualisation/reconstruction/val_ok_front_hist.png:
        cache: false
    - visualisation/reconstruction/train_def_front_hist.png:
        cache: false
    - visualisation/reconstruction/val_def_front_hist.png:
        cache: false

# *** ---------------------------------------------

  complexity_vs_caemse:
    cmd: python3 src/complexity_vs_caemse.py
    deps:
    - src/complexity_vs_caemse.py
    - data/processed/tabular/complexity.csv
    - data/processed/tabular/cae_mse.csv
    plots:
    - visualisation/complexity_vs_caemse.html:
        cache: false

# *** ---------------------------------------------

  cae_mse_model:
    cmd: python3 src/cae_mse_model.py
    deps:
    - src/cae_mse_model.py
    - src/utils/models/threshold_search.py
    - data/processed/tabular/cae_mse.csv
    params:
    - cae_mse_model.score_func
    - cae_mse_model.n_iter
    outs:
    - models/params/mse_threshold.txt
    - visualisation/thresholds/mse.html:
        cache: false

# *** ---------------------------------------------

  corrected_model:
    cmd: python3 src/corrected_model.py
    deps:
    - src/corrected_model.py
    - src/utils/models/threshold_search.py
    - data/processed/tabular/cae_mse.csv
    params:
    - corrected_model.score_func
    - corrected_model.n_iter
    outs:
    - models/params/corrected_mse_threshold.txt
    - visualisation/thresholds/corrected_mse.html:
        cache: false


# *** ---------------------------------------------

  evaluate:
    cmd: python3 src/evaluate.py
    deps:
    - src/evaluate.py
    - src/utils/evaluation/classification_metrics.py
    - data/processed/tabular/cae_mse.csv
    - models/params/mse_threshold.txt
    - models/params/corrected_mse_threshold.txt
    metrics:
    - metrics/cae_metrics.json:
        cache: false
    - metrics/corrected_cae_metrics.json:
        cache: false
