stages:
  train_test_split:
    cmd: python3 src/train_test_split.py
    deps:
    - src/train_test_split.py
    - src/utils/dvc/params.py
    - data/raw
    params:
    - train_test_split.split_ratio
    - train_test_split.shuffle
    - train_test_split.seed
    outs:
    - data/processed/train
    - data/processed/test

# *** ---------------------------------------------

  augmentation_visualisation:
    cmd: python3 src/augmentation_visualisation.py
    deps:
    - src/augmentation_visualisation.py
    - src/utils/data/tfdatasets.py
    - src/utils/dvc/params.py
    - data/processed/train
    params:
    - all.random_crop
    - all.random_flip
    - all.random_rotation
    - all.random_zoom
    - all.random_brightness
    - all.random_contrast
    - all.random_translation_height
    - all.random_translation_width
    plots:
    - visualisation/augmentation/augmented_images.png:
        cache: false

# *** ---------------------------------------------

  extract_complexity:
    cmd: python3 src/extract_complexity.py
    deps:
    - src/extract_complexity.py
    - src/utils/data/jpegmse.py
    - src/utils/data/complexityaux.py
    - data/processed/train
    - data/processed/test
    outs:
    - data/processed/tabular/complexity.csv
    plots:
    - visualisation/complexity/train_ok_front.png:
        cache: false
    - visualisation/complexity/test_ok_front.png:
        cache: false
    - visualisation/complexity/train_def_front.png:
        cache: false
    - visualisation/complexity/test_def_front.png:
        cache: false
