all:   # Parameters used in multiple stages
  random_crop:
  - 224
  - 224
  random_flip: horizontal
  random_rotation: 0
  random_zoom:
  - -0.1
  - 0.1
  random_brightness: 0.2
  random_contrast: 0.2
  random_translation_height:
  - -0.1
  - 0.1
  random_translation_width:
  - -0.1
  - 0.1
  input_size:
  - 256
  - 256
  - 3
  seed: 13
  dataset: streets
  grayscale: false
  scale: 255
  models_n_iter: 25
  models_score_func: f1
  models_balanced: false
dataset_split:
  split_ratio:
  - 0.8
  - 0.1
  - 0.1
  shuffle: true
cae_hp_tuning:
  batch_size: 4
  bottleneck_filters: 128
  alpha: 0.98
  beta: 0.93
  patience: 3
  revive_best: true
  early_stopping: false
  epochs: 25
  min_lr: 0.000001
  max_trials: 30
cae_pretraining:
  batch_size: 4
  alpha: 0.98
  beta: 0.9
  patience: 3
  revive_best: false
  early_stopping: true
  epochs: 10
  min_lr: 0.00001
  learning_rate: 0.0015
cae_training:
  batch_size: 4
  alpha: 0.98
  beta: 0.93
  patience: 5
  revive_best: true
  early_stopping: false
  epochs: 100
  min_lr: 0.00001
  learning_rate: 0.0005