all:   # Parameters used in multiple stages
  random_crop:
  - 224
  - 224
  random_flip: horizontal
  random_rotation: 0.05
  random_zoom:
  - -0.1
  - 0.1
  random_brightness: 0.15
  random_contrast: 0.15
  random_translation_height:
  - -0.15
  - 0.15
  random_translation_width:
  - -0.15
  - 0.15
  input_size:
  - 232
  - 232
  - 1
  seed: 13
  dataset: streets
  grayscale: false
  scale: 255

dataset_split:
  split_ratio:
  - 0.8
  - 0.1
  - 0.1
  shuffle: true

cae_hp_tuning:
  batch_size: 4
  bottleneck_filters: 32
  alpha: 0.98
  beta: 0.93
  patience: 5
  revive_best: true
  early_stopping: false
  epochs: 130
  min_lr: 0.000001
  max_trials: 100

cae_pretraining:
  pretrain: false
  batch_size: 8
  alpha: 0.98
  beta: 0.93
  patience: 3
  revive_best: false
  early_stopping: true
  epochs: 2
  min_lr: 0.00001
  learning_rate: 0.0015

cae_training:
  batch_size: 8
  alpha: 0.98
  beta: 0.93
  patience: 5
  revive_best: true
  early_stopping: false
  epochs: 130
  min_lr: 0.00001

train_classifier_models:
  models_n_iter: 25
  models_n_splits: 10
  models_score_func: f1