all:   # Parameters used in multiple stages
  random_crop:
  - 224
  - 224
  random_flip: horizontal_and_vertical
  random_rotation: 0.8
  random_zoom:
  - -0.05
  - 0.05
  random_brightness: 0.05
  random_contrast: 0.05
  random_translation_height:
  - -0.05
  - 0.05
  random_translation_width:
  - -0.05
  - 0.05
  input_size:
  - 256
  - 256
  - 3
  seed: 13
  dataset: casting
  grayscale: true
  scale: 255

dataset_split:
  split_ratio:
  - 0.8
  - 0.1
  - 0.1
  shuffle: true

cae_hp_tuning:
  batch_size: 16
  bottleneck_filters: 64
  alpha: 0.98
  beta: 0.93
  patience: 5
  revive_best: true
  early_stopping: false
  epochs: 1
  min_lr: 0.000001
  max_trials: 1

cae_pretraining:
  pretrain: false
  batch_size: 8
  alpha: 0.98
  beta: 0.93
  patience: 3
  revive_best: false
  early_stopping: true
  epochs: 2
  min_lr: 0.00001
  learning_rate: 0.0015

cae_training:
  batch_size: 16
  alpha: 0.98
  beta: 0.93
  patience: 5
  revive_best: true
  early_stopping: false
  epochs: 100
  min_lr: 0.00001

train_classifier_models:
  models_n_iter: 25
  models_n_splits: 10
  models_score_func: f1