all:   # Parameters used in multiple stages
  random_crop: [224, 224]
  random_flip: 'horizontal_and_vertical'
  random_rotation: 0.4
  random_zoom: [-0.1, 0.1]
  random_brightness: 0.2
  random_contrast: 0.2
  random_translation_height: [-0.1, 0.1]
  random_translation_width: [-0.1, 0.1]
train_test_split:
  split_ratio: 0.8
  shuffle: true
  seed: 14