all:   # Parameters used in multiple stages
  random_crop: [224, 224]
  random_flip: 'horizontal_and_vertical'
  random_rotation: 0.4
  random_zoom: [-0.1, 0.1]
  random_brightness: 0.2
  random_contrast: 0.2
  random_translation_height: [-0.1, 0.1]
  random_translation_width: [-0.1, 0.1]
  input_size: [256, 256, 1]
  seed: 13
  dataset: 'casting'
  grayscale: true
  scale: 255
dataset_split:
  split_ratio: [0.7, 0.1, 0.2]
  shuffle: true
cae_hp_tuning:
  batch_size: 4
  bottleneck_filters: 64
  alpha: 0.98
  beta: 0.9
  patience: 3
  revive_best: true
  early_stopping: false
  epochs: 15
  min_lr: 0.000001
  max_trials: 50
cae_pretraining:
  batch_size: 2
  alpha: 0.98
  beta: 0.9
  patience: 3
  revive_best: true
  early_stopping: false
  epochs: 5
  min_lr: 0.00001
  learning_rate: 0.001
cae_training:
  batch_size: 8
  alpha: 0.98
  beta: 0.9
  patience: 3
  revive_best: true
  early_stopping: false
  epochs: 50
  min_lr: 0.00001
  learning_rate: 0.0005
cae_mse_model:
  n_iter: 25
  score_func: 'accuracy'
  balanced: true
corrected_model:
  n_iter: 25
  score_func: 'accuracy'
  balanced: true